/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Cliente;
import Modal.AdcCliente2;
import Models.ModelCliente;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luan
 */
public class FrameClientes extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;
    private int quantidade, i=0; //Saber a quantidade de itens para o SELECT
    private String selecionado1, selecionado2; //Saber quais itens serão usados no SELECT
    private String conteudo1, conteudo2; //Conteudo dos campos selecionados para o SELECT
    ModelCliente mc = new ModelCliente();
    Cliente p = new Cliente();
    
    /**
     * Creates new form FrameClientes
     */
    public FrameClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void centralizar(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Nome1 = new javax.swing.JRadioButton();
        Email1 = new javax.swing.JRadioButton();
        ID1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Data1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Data = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        semFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        Editar = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(472, 156));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setToolTipText("Escolha temas para pesquisar.\n\"Data\" pode ser combinado com qualquer outro.");

        Nome1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Nome1);
        Nome1.setText("Nome");

        Email1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Email1);
        Email1.setText("E-Mail");
        Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1ActionPerformed(evt);
            }
        });

        ID1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(ID1);
        ID1.setText("ID");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Data1.setBackground(new java.awt.Color(153, 153, 255));
        Data1.setText("Data");
        Data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ID1)
                        .addGap(20, 20, 20)
                        .addComponent(Nome1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Email1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Data1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID1)
                    .addComponent(Nome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email1)
                    .addComponent(Data1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel2.setText("Nome");

        ID.setEnabled(false);

        Nome.setEnabled(false);

        jLabel3.setText("Data");

        Email.setEnabled(false);

        try {
            Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Data.setEnabled(false);
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel4.setText("E-Mail");

        Confirmar.setText("Pesquisar");
        Confirmar.setAutoscrolls(true);
        Confirmar.setEnabled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        semFiltro.setText("Sem Filtro");
        semFiltro.setToolTipText("Não usar filtros de pesquisa.");
        semFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semFiltro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(semFiltro))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setAutoscrolls(true);

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-Mail", "Fone", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TabelaCliente);
        if (TabelaCliente.getColumnModel().getColumnCount() > 0) {
            TabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Apagar.setText("Apagar");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Editar)
                            .addComponent(Apagar)
                            .addComponent(Cadastrar))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Apagar, Cadastrar, Editar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Apagar, Cadastrar, Editar});

        setBounds(0, 0, 893, 500);
    }// </editor-fold>//GEN-END:initComponents

    // INICIO DE MÉTODOS PARA A TABELA
    //===================================///======================================
    
    private void montarTabela(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        //ModelCliente mc = new ModelCliente();
        for (Cliente c : mc.listaClientes()){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone(), c.getData()});
        }
    }
    
    private void montarTabela1(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        //ModelCliente mc = new ModelCliente();
        if(mc.listaClientes1(selecionado1, conteudo1)==null){
            JOptionPane.showMessageDialog(this, mc.exibirErro()); 
        }else{
            //JOptionPane.showMessageDialog(this, conteudo1);
            for (Cliente c : mc.listaClientes1(selecionado1, conteudo1)){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone(), c.getData()});
        }
        }
    }
    
    private void montarTabela2(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        //ModelCliente mc = new ModelCliente();
        for (Cliente c : mc.listaClientes2(selecionado1, conteudo1, selecionado2, conteudo2)){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone(), c.getData()});
        }
        
    }
    
    private void limparTabela(){
        tabela.setNumRows(0);
    }
    
    public int getQuantidade() {
        return quantidade;
    }

    public String getSelecionado1() {
        return selecionado1;
    }

    public String getSelecionado2() {
        return selecionado2;
    }

    public String getConteudo1() {
        return conteudo1;
    }

    public String getConteudo2() {
        return conteudo2;
    }
    
    //===================================///======================================
    // FIM DE MÉTODOS PARA A TABELA
    
    
    
    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
        if (Confirmar.getText().equals("Pesquisar")){ // DECIDIR SESERÁ SELEC OU UPDATE
            
            if (ID1.isSelected() && Data1.isSelected()){
            conteudo1 = ID.getText();
            conteudo2 = Data.getText();

            }else if(ID1.isSelected()){
                conteudo1 = ID.getText();

            }else if(Nome1.isSelected() && Data1.isSelected()){
                conteudo1 = Nome.getText();
                conteudo2 = Data.getText();

            }else if(Nome1.isSelected()){
                conteudo1 = Nome.getText();

            }else if(Email1.isSelected() && Data1.isSelected()){
                conteudo1 = Email.getText();
                conteudo2 = Data.getText();

            }else if(Email1.isSelected()){
                conteudo1 = Email.getText();

            }else if(Data1.isSelected()){
                conteudo1 = Data.getText();

            }else{
                quantidade = 0;
                JOptionPane.showMessageDialog(this, "Exibindo resultado sem filtros de pesquisa.");
            }

            
            if (i==1){
              limparTabela();  
            }
            switch (getQuantidade()) {
                case 0:
                    try{montarTabela();
                    }catch(Exception e){ JOptionPane.showMessageDialog(this, e);
                    i=1;
                    }
                    
                    break;
                case 1:
                    try{montarTabela1();
                    }catch(Exception e){ JOptionPane.showMessageDialog(this, e);
                    i=1;
                    }
                    break;
                case 2:
                    montarTabela2();
                    i=1;
                    break;
                default:
                    break;
            }
            
        }else{
            
            p.setNome(Nome.getText());
            p.setEmail(Email.getText());
            
            if (mc.editar(p)==true){
                JOptionPane.showMessageDialog(this, "Cliente editado com sucesso!");
                ID.setText(null); ID.setEnabled(false);
                Nome.setText(null); Nome.setEnabled(false);
                Email.setText(null); Email.setEnabled(false);
                Confirmar.setText("Pesquisar"); Confirmar.setEnabled(false);
                semFiltro.setEnabled(true);
                limparTabela(); montarTabela();
            }else{
                JOptionPane.showMessageDialog(this, mc.exibirErro());
            }
            
        }
        

    }//GEN-LAST:event_ConfirmarActionPerformed

    private void Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (ID1.isSelected() && Data1.isSelected()){
            ID.setEnabled(true);
            Data.setEnabled(true);
            Nome.setEnabled(false); Nome.setText(null);
            Email.setEnabled(false);Email.setText(null);
            Confirmar.setEnabled(true);

            quantidade = 2;
            selecionado1 = "id";
            selecionado2 = "data";

        }else if(ID1.isSelected()){
            ID.setEnabled(true);
            Data.setEnabled(false); Data.setText(null);
            Nome.setEnabled(false); Nome.setText(null);
            Email.setEnabled(false); Email.setText(null);
            Confirmar.setEnabled(true);

            quantidade = 1;
            selecionado1 = "id";

        }else if(Nome1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false); ID.setText(null);
            Data.setEnabled(true);
            Nome.setEnabled(true);
            Email.setEnabled(false); Email.setText(null);
            Confirmar.setEnabled(true);

            quantidade = 2;
            selecionado1 = "nome";
            selecionado2 = "data";

        }else if(Nome1.isSelected()){
            ID.setEnabled(false); ID.setText(null);
            Data.setEnabled(false); Data.setText(null);
            Nome.setEnabled(true);
            Email.setEnabled(false); Email.setText(null);
            Confirmar.setEnabled(true);

            quantidade = 1;
            selecionado1 = "nome";

        }else if(Email1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false); ID.setText(null);
            Data.setEnabled(true);
            Nome.setEnabled(false); Nome.setText(null);
            Email.setEnabled(true);
            Confirmar.setEnabled(true);

            quantidade = 2;
            selecionado1 = "email";
            selecionado2 = "data";

        }else if(Email1.isSelected()){
            ID.setEnabled(false); ID.setText(null);
            Data.setEnabled(false); Data.setText(null);
            Nome.setEnabled(false); Nome.setText(null);
            Email.setEnabled(true);
            Confirmar.setEnabled(true);

            quantidade = 1;
            selecionado1 = "email";

        }else if(Data1.isSelected()){
            ID.setEnabled(false); ID.setText(null);
            Data.setEnabled(true);
            Nome.setEnabled(false); Nome.setText(null);
            Email.setEnabled(false); Email.setText(null);
            Confirmar.setEnabled(true);

            quantidade = 1;
            selecionado1 = "data";

        }else{
            JOptionPane.showMessageDialog(this, "É preciso selecionar ao menos um tema de pesquisa.");
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        centralizar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        
        if (TabelaCliente.getSelectedRowCount()<1){
            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado.");
        }else if (TabelaCliente.getSelectedRowCount()>1){
            JOptionPane.showMessageDialog(this, "Por favor, selecione apenas um cliente por vez para edita-lo.");
        }else{
            Long idLocal = (Long)TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 0);
            p = mc.buscar(idLocal);
            ID.setText(Long.toString(p.getId())); ID.setEnabled(false);
            Nome.setText(p.getNome()); Nome.setEnabled(true);
            Email.setText(p.getEmail()); Email.setEnabled(true);
            Data.setText(p.getData()); Data.setEnabled(false);
            Confirmar.setText("Salvar"); Confirmar.setEnabled(true);
            semFiltro.setEnabled(false);
            JOptionPane.showMessageDialog(this, p.getData());
            
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        // TODO add your handling code here:
        if(TabelaCliente.getSelectedRowCount()>1){
            JOptionPane.showMessageDialog(this, "Selecione apenas um cliente por vez para deleta-lo.");
        }else if(TabelaCliente.getSelectedRowCount()<1){
            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado.");
        }else{
            Long n = (Long)TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 0);
            System.out.println(n);
            int botao;
        botao = JOptionPane.showConfirmDialog (null, "Tem certeza que deseja apagar?", "Aviso", JOptionPane.YES_OPTION);
        if(botao == JOptionPane.YES_OPTION){
           mc.delete(n);
           limparTabela(); montarTabela();
        }
        }
        
    }//GEN-LAST:event_ApagarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
         AdcCliente2 ac = new AdcCliente2();
         ac.setModal(true);
         ac.setVisible(true);
    }//GEN-LAST:event_CadastrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void semFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semFiltroActionPerformed
        // TODO add your handling code here:

        /*quantidade = 0;
        FrameExibirCliente fec = new FrameExibirCliente();
        fec.setValores(this.selecionado1, this.selecionado2, this.conteudo1, this.conteudo2, this.quantidade);
        fec.setVisible(true);*/
        if (i==1){
            limparTabela();
        }
        montarTabela();
        i=1;
    }//GEN-LAST:event_semFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JFormattedTextField Data;
    private javax.swing.JRadioButton Data1;
    private javax.swing.JButton Editar;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Email1;
    private javax.swing.JTextField ID;
    private javax.swing.JRadioButton ID1;
    private javax.swing.JTextField Nome;
    private javax.swing.JRadioButton Nome1;
    private javax.swing.JTable TabelaCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton semFiltro;
    // End of variables declaration//GEN-END:variables
}
