/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Cliente;
import Models.ModelCliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luan
 */
public class FrameExibirCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrameExibirCliente
     */
    public FrameExibirCliente() {
        initComponents();
        i = 0;
        /*if(getQuantidade()==0){
            montarTabela();
        }else if(getQuantidade()==1){
            montarTabela1();
        }else if(getQuantidade()==2){
            montarTabela2();
        }
        //System.out.println("SELECT c FROM Clientes c WHERE c."+selecionado1+" = '"+conteudo1+"'");
        System.out.println(getSelecionado1());*/
    }

    DefaultTableModel tabela;
    private int i; //controle
    private int quantidade; //Saber a quantidade de itens para o SELECT
    private String selecionado1, selecionado2; //Saber quais itens serão usados no SELECT
    private String conteudo1, conteudo2; //Conteudo dos campos selecionados para o SELECT
    
    private void montarTabela(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        ModelCliente mc = new ModelCliente();
        for (Cliente c : mc.listaClientes()){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone()});
        }
    }
    
    private void montarTabela1(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        ModelCliente mc = new ModelCliente();
        for (Cliente c : mc.listaClientes1(selecionado1, conteudo1)){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone()});
        }
    }
    
    private void montarTabela2(){
        tabela = (DefaultTableModel) TabelaCliente.getModel();
        ModelCliente mc = new ModelCliente();
        for (Cliente c : mc.listaClientes2(selecionado1, conteudo1, selecionado2, conteudo2)){
            tabela.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone()});
        }
    }
    
    public void setValores(String selecionado1, String selecionado2, String conteudo1, String conteudo2, int quantidade){
        this.selecionado1 = selecionado1;
        this.selecionado2 = selecionado2;
        this.conteudo1 = conteudo1;
        this.conteudo2 = conteudo2;
        this.quantidade = quantidade;
    }

    public int getQuantidade() {
        return quantidade;
    }

    public String getSelecionado1() {
        return selecionado1;
    }

    public String getSelecionado2() {
        return selecionado2;
    }

    public String getConteudo1() {
        return conteudo1;
    }

    public String getConteudo2() {
        return conteudo2;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-Mail", "Fone", "Comandos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (i == 0){
            i = 1;
            if(getQuantidade()==0){
            montarTabela();
        }else if(getQuantidade()==1){
            montarTabela1();
        }else if(getQuantidade()==2){
            montarTabela2();
        }
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExibirCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
