/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Cliente;
import Entidades.Funcionario;
import Entidades.Venda;
import Modal.AdcVenda;
import Modal.AdcVenda2;
import Models.ModelFuncionario;
import Models.ModelVenda;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luan
 */
public class FrameVenda extends javax.swing.JInternalFrame {

    DefaultTableModel tabela;
    private int quantidade, i=0; //Saber a quantidade de itens para o SELECT
    private String selecionado1, selecionado2; //Saber quais itens serão usados no SELECT
    private String conteudo1, conteudo2; //Conteudo dos campos selecionados para o SELECT
    ModelVenda mv = new ModelVenda();
    ModelFuncionario mf = new ModelFuncionario();
    Funcionario logado = new Funcionario();
    Venda p = new Venda();
    /**
     * Creates new form FrameVenda
     */
    public FrameVenda() {
        initComponents();
    }
    
    public void centralizar(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    // INICIO DE MÉTODOS PARA A TABELA
    //===================================///======================================
    
    private void montarTabela(){
        tabela = (DefaultTableModel) Tabela.getModel();
        //ModelCliente mc = new ModelCliente();
        for (Venda v : mv.listaVendas()){
            tabela.addRow(new Object[]{v.getId(), v.getVendedor(), v.getCliente(), v.getQuantidade(), v.getValortotal(), v.getData()});
        }
    }
    
    private void montarTabela1(){
        tabela = (DefaultTableModel) Tabela.getModel();
        //ModelCliente mc = new ModelCliente();
        if(mv.listaVendas1(selecionado1, conteudo1)==null){
            JOptionPane.showMessageDialog(this, mv.exibirErro()); 
        }else{
            for (Venda v : mv.listaVendas1(selecionado1, conteudo1)){
            tabela.addRow(new Object[]{v.getId(), v.getVendedor(), v.getCliente(), v.getQuantidade(), v.getValortotal(), v.getData()});
        }
        }
    }
    
    private void montarTabela2(){
        tabela = (DefaultTableModel) Tabela.getModel();
        //ModelCliente mc = new ModelCliente();
        for (Venda v : mv.listaVendas2(selecionado1, conteudo1, selecionado2, conteudo2)){
            tabela.addRow(new Object[]{v.getId(), v.getVendedor(), v.getCliente(), v.getQuantidade(), v.getValortotal(), v.getData()});
        }
        
    }
    
    private void limparTabela(){
        tabela.setNumRows(0);
    }
    
    public int getQuantidade() {
        return quantidade;
    }

    public String getSelecionado1() {
        return selecionado1;
    }

    public String getSelecionado2() {
        return selecionado2;
    }

    public String getConteudo1() {
        return conteudo1;
    }

    public String getConteudo2() {
        return conteudo2;
    }
    
    //===================================///======================================
    // FIM DE MÉTODOS PARA A TABELA
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ID = new javax.swing.JTextField();
        Valor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Data = new javax.swing.JTextField();
        Vendedor = new javax.swing.JTextField();
        Quantidade = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        semFiltro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Vendedor1 = new javax.swing.JRadioButton();
        Data1 = new javax.swing.JRadioButton();
        Valor1 = new javax.swing.JRadioButton();
        Cliente1 = new javax.swing.JRadioButton();
        ID1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Quantidade1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vendas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        ID.setEnabled(false);

        Valor.setEnabled(false);

        jLabel4.setText("Cliente");

        Data.setEnabled(false);

        Vendedor.setEnabled(false);

        Quantidade.setEnabled(false);

        Cliente.setEnabled(false);

        jLabel5.setText("Quantidade");

        jLabel2.setText("Data");

        jLabel1.setText("ID");

        jLabel3.setText("Vendedor");

        jLabel6.setText("Valor");

        Confirmar.setText("Pesquisar");
        Confirmar.setEnabled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        semFiltro.setText("Sem filtro");
        semFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Valor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semFiltro)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(semFiltro))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        Vendedor1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Vendedor1);
        Vendedor1.setText("Vendedor(a)");
        Vendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendedor1ActionPerformed(evt);
            }
        });

        Data1.setBackground(new java.awt.Color(153, 153, 255));
        Data1.setText("Data");
        Data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data1ActionPerformed(evt);
            }
        });

        Valor1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Valor1);
        Valor1.setText("Valor");
        Valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor1ActionPerformed(evt);
            }
        });

        Cliente1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Cliente1);
        Cliente1.setText("Cliente");
        Cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente1ActionPerformed(evt);
            }
        });

        ID1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(ID1);
        ID1.setText("ID");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Quantidade1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(Quantidade1);
        Quantidade1.setText("Quantidade");
        Quantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantidade1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID1)
                            .addComponent(Cliente1)
                            .addComponent(Valor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Data1)
                            .addComponent(Quantidade1)
                            .addComponent(Vendedor1))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID1)
                    .addComponent(Quantidade1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vendedor1)
                    .addComponent(Cliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor1)
                    .addComponent(Data1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vendedor", "Cliente", "Quantidade", "Valor Total", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jButton2.setText("Adicionar venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Quantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantidade1ActionPerformed

    private void Vendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vendedor1ActionPerformed

    private void Cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente1ActionPerformed

    private void Valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor1ActionPerformed

    private void Data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(ID1.isSelected() && Data1.isSelected()){
            ID.setEnabled(true);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 2;
            selecionado1 = "id";
            selecionado2 = "data";
            
        }else if(ID1.isSelected()){
            ID.setEnabled(true);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(false);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "id";
            
        }else if(Vendedor1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(true);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 2;
            selecionado1 = "vendedor";
            selecionado2 = "data";
            
        }else if(Vendedor1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(true);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(false);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "vendedor";
            
        }else if(Cliente1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(true);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 2;
            selecionado1 = "cliente";
            selecionado2 = "data";
            
        }else if(Cliente1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(true);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(false);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "cliente";
            
        }else if(Quantidade1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(true);
            Valor.setEnabled(false);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 2;
            selecionado1 = "quantidade";
            selecionado2 = "data";
            
        }else if(Quantidade1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(true);
            Valor.setEnabled(false);
            Data.setEnabled(false);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "quantidade";
            
        }else if(Valor1.isSelected() && Data1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(true);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 2;
            selecionado1 = "valortotal";
            selecionado2 = "data";
            
        }else if(Valor1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(true);
            Data.setEnabled(false);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "valortotal";
            
        }else if(Valor1.isSelected()){
            ID.setEnabled(false);
            Vendedor.setEnabled(false);
            Cliente.setEnabled(false);
            Quantidade.setEnabled(false);
            Valor.setEnabled(false);
            Data.setEnabled(true);
            Confirmar.setEnabled(true);
            
            quantidade = 1;
            selecionado1 = "data";
            
        }else{
            JOptionPane.showMessageDialog(this, "É preciso selecionar ao menos um tema de pesquisa.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
        
        if(ID1.isSelected() && Data1.isSelected()){
            conteudo1 = ID.getText();
            conteudo2 = Data.getText();
            
        }else if(ID1.isSelected()){
            conteudo1 = ID.getText();
            
        }else if(Vendedor1.isSelected() && Data1.isSelected()){
            conteudo1 = Vendedor.getText();
            conteudo2 = Data.getText();
            
        }else if(Vendedor1.isSelected()){
            conteudo1 = Vendedor.getText();
            
        }else if(Cliente1.isSelected() && Data1.isSelected()){
            conteudo1 = Cliente.getText();
            conteudo2 = Data.getText();
            
        }else if(Cliente1.isSelected()){
            conteudo1 = Cliente.getText();
            
        }else if(Quantidade1.isSelected() && Data1.isSelected()){
            conteudo1 = Quantidade.getText();
            conteudo2 = Data.getText();
            
        }else if(Quantidade1.isSelected()){
            conteudo1 = Quantidade.getText();
            
        }else if(Valor1.isSelected() && Data1.isSelected()){
            conteudo1 = Valor.getText();
            conteudo2 = Data.getText();
            
        }else if(Valor1.isSelected()){
            conteudo1 = Valor.getText();
            
        }else if(Valor1.isSelected()){
            conteudo1 = Data.getText();
            
        }else{
            quantidade = 0;
            JOptionPane.showMessageDialog(this, "Exibindo resultado sem filtros de pesquisa.");
        }
        
        if (i==1){
              limparTabela();  
        }
        switch (getQuantidade()) {
            case 0:
                montarTabela();
                i=1;
                break;
            case 1:
                montarTabela1();
                i=1;
                break;
            case 2:
                montarTabela2();
                i=1;
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void semFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semFiltroActionPerformed
        // TODO add your handling code here:
        
        if (i==1){
            limparTabela();
        }
        montarTabela();
        i=1;
        
    }//GEN-LAST:event_semFiltroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            AdcVenda2 av = new AdcVenda2();
            av.logado = this.logado;
            av.setModal(true);
            av.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        centralizar();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente;
    private javax.swing.JRadioButton Cliente1;
    private javax.swing.JButton Confirmar;
    private javax.swing.JTextField Data;
    private javax.swing.JRadioButton Data1;
    private javax.swing.JTextField ID;
    private javax.swing.JRadioButton ID1;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JRadioButton Quantidade1;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField Valor;
    private javax.swing.JRadioButton Valor1;
    private javax.swing.JTextField Vendedor;
    private javax.swing.JRadioButton Vendedor1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton semFiltro;
    // End of variables declaration//GEN-END:variables
}
