/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Funcionario;
import Entidades.Produto;
import Modal.Vender;
import Models.ModelFuncionario;
import Models.ModelProduto;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan
 */
public class FrameMenu extends javax.swing.JFrame {

    ModelFuncionario mf = new ModelFuncionario();
    ModelProduto mp = new ModelProduto();
    Funcionario logado = new Funcionario();
    int R = 0; //cuidar do array
    private FrameFuncionario ff;
    private FrameClientes fc;
    private FrameFornecedor ffo;
    private FrameVenda fv;
    private FrameProduto fp;

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
        //System.out.println(logado.getId()+","+logado.getNome());
    }

    public boolean todosProdutos() {
        try {
            for (Produto p : mp.listaProdutos()) {
                if (p.getEstoque() <= p.getEstoqueMin()) {
                    return true;
                }
            }
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            return false;
        }

    }

    /*public void todosProdutos() {
        try {
            for (Produto p : mp.listaProdutos()) {
                if (p.getEstoque() <= p.getEstoqueMin()) {
                    R++;
                    nomeP[R] = p.getNome();
                    System.out.println(p.getNome()+"==="+R);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }*/
    public void aviso() {
        if (todosProdutos() == true) {

            FrameAviso fa = new FrameAviso();
            Desktop.add(fa);
            fa.montarTabela();
            //fa.R = this.R;
            fa.show();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Produtos2 = new javax.swing.JButton();
        Fornecedores3 = new javax.swing.JButton();
        Cliente2 = new javax.swing.JButton();
        Vendas2 = new javax.swing.JButton();
        Fornecedores2 = new javax.swing.JButton();
        RH2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Gerente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Desktop.setBackground(new java.awt.Color(255, 255, 255));
        Desktop.setMaximumSize(new java.awt.Dimension(571, 478));
        Desktop.setMinimumSize(new java.awt.Dimension(571, 478));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(21, 116, 253));

        Produtos2.setBackground(new java.awt.Color(114, 172, 254));
        Produtos2.setText("PRODUTOS");
        Produtos2.setBorderPainted(false);
        Produtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos2ActionPerformed(evt);
            }
        });

        Fornecedores3.setBackground(new java.awt.Color(114, 172, 254));
        Fornecedores3.setText("LOGOUT");
        Fornecedores3.setBorderPainted(false);
        Fornecedores3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fornecedores3ActionPerformed(evt);
            }
        });

        Cliente2.setBackground(new java.awt.Color(114, 172, 254));
        Cliente2.setText("CLIENTES");
        Cliente2.setToolTipText("Cliente");
        Cliente2.setBorderPainted(false);
        Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente2ActionPerformed(evt);
            }
        });

        Vendas2.setBackground(new java.awt.Color(114, 172, 254));
        Vendas2.setText("VENDAS");
        Vendas2.setToolTipText("Vendas");
        Vendas2.setBorderPainted(false);
        Vendas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendas2ActionPerformed(evt);
            }
        });

        Fornecedores2.setBackground(new java.awt.Color(114, 172, 254));
        Fornecedores2.setText("FORNECEDORES");
        Fornecedores2.setBorderPainted(false);
        Fornecedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fornecedores2ActionPerformed(evt);
            }
        });

        RH2.setBackground(new java.awt.Color(114, 172, 254));
        RH2.setText("RECURSOS HUMANOS");
        RH2.setToolTipText("Recursos Humanos");
        RH2.setBorderPainted(false);
        RH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RH2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RH2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(Cliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vendas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Produtos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fornecedores2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fornecedores3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Vendas2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Produtos2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fornecedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fornecedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cliente2, Fornecedores2, Produtos2, RH2, Vendas2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openForm(JInternalFrame f) {
        Desktop.add(f);
        //f.centralizar();
        f.show();
    }

    private void RH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RH2ActionPerformed
        // TODO add your handling code here:
        try {
            ff.isVisible();
            ff.toFront();
        } catch (Exception e) {
            ff = new FrameFuncionario();
            //ff.logado = this.logado;
            Desktop.add(ff);
            ff.show();
        }

    }//GEN-LAST:event_RH2ActionPerformed

    private void Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente2ActionPerformed
        // TODO add your handling code here:

        try {
            fc.isVisible();
            fc.toFront();
        } catch (Exception e) {
            fc = new FrameClientes();
            //fv.logado = this.logado;
            Desktop.add(fc);
            fc.show();
        }
    }//GEN-LAST:event_Cliente2ActionPerformed

    private void Vendas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendas2ActionPerformed
        // TODO add your handling code here:
        //openForm(new FrameVenda());

        try {
            fv.isVisible();
            fv.toFront();
        } catch (Exception e) {
            fv = new FrameVenda();
            fv.logado = this.logado;
            Desktop.add(fv);
            fv.show();
        }
    }//GEN-LAST:event_Vendas2ActionPerformed

    private void Produtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos2ActionPerformed
        // TODO add your handling code here:

        try {
            fp.isVisible();
            fp.toFront();
        } catch (Exception e) {
            fp = new FrameProduto();
            //fp.logado = this.logado;
            Desktop.add(fp);
            fp.show();
        }
    }//GEN-LAST:event_Produtos2ActionPerformed

    private void Fornecedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fornecedores2ActionPerformed
        // TODO add your handling code here:

        try {
            ffo.isVisible();
            ffo.toFront();
        } catch (Exception e) {
            ffo = new FrameFornecedor();
            //fv.logado = this.logado;
            Desktop.add(ffo);
            ffo.show();
        }
    }//GEN-LAST:event_Fornecedores2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //painel();
        aviso();
    }//GEN-LAST:event_formWindowOpened

    private void Fornecedores3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fornecedores3ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Fornecedores3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente2;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton Fornecedores2;
    private javax.swing.JButton Fornecedores3;
    private javax.swing.JButton Produtos2;
    private javax.swing.JButton RH2;
    private javax.swing.JButton Vendas2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
