/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Produto;
import Models.ModelProduto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luan
 */
public class FrameExibirProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrameExibirProduto
     */
    public FrameExibirProduto() {
        initComponents();
        
    }

    DefaultTableModel tabela;
    private int quantidade; //Saber a quantidade de itens para o SELECT
    private String selecionado1, selecionado2; //Saber quais itens serão usados no SELECT
    private String conteudo1, conteudo2; //Conteudo dos campos selecionados para o SELECT
    
    private void montarTabela(){
        tabela = (DefaultTableModel) Tabela.getModel();
        ModelProduto mp = new ModelProduto();
        for (Produto p : mp.listaProdutos()){
            tabela.addRow(new Object[]{p.getId(), p.getNome(), p.getDescricao(), p.getTipo(), p.getEstoque(),
                p.getValorVenda(), p.getValorCompra(), p.getCnpj_fornecedor(), p.getTamanho(), p.getEstoqueMin()});
        }
    }
    
    private void montarTabela1(){
        tabela = (DefaultTableModel) Tabela.getModel();
        ModelProduto mp = new ModelProduto();
        for (Produto p : mp.listaProdutos1(selecionado1, conteudo1)){
            tabela.addRow(new Object[]{p.getId(), p.getNome(), p.getDescricao(), p.getTipo(), p.getEstoque(),
                p.getValorVenda(), p.getValorCompra(), p.getCnpj_fornecedor(), p.getTamanho(), p.getEstoqueMin()});
        }
    }
    
    private void montarTabela2(){
        tabela = (DefaultTableModel) Tabela.getModel();
        ModelProduto mp = new ModelProduto();
        for (Produto p : mp.listaProdutos2(selecionado1, conteudo1, selecionado2, conteudo2)){
            tabela.addRow(new Object[]{p.getId(), p.getNome(), p.getDescricao(), p.getTipo(), p.getEstoque(),
                p.getValorVenda(), p.getValorCompra(), p.getCnpj_fornecedor(), p.getTamanho(), p.getEstoqueMin()});
        }
    }
    
    public void setValores(String selecionado1, String selecionado2, String conteudo1, String conteudo2, int quantidade){
        this.selecionado1 = selecionado1;
        this.selecionado2 = selecionado2;
        this.conteudo1 = conteudo1;
        this.conteudo2 = conteudo2;
        this.quantidade = quantidade;
    }

    public int getQuantidade() {
        return quantidade;
    }

    public String getSelecionado1() {
        return selecionado1;
    }

    public String getSelecionado2() {
        return selecionado2;
    }

    public String getConteudo1() {
        return conteudo1;
    }

    public String getConteudo2() {
        return conteudo2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Tipo", "Estoque", "Valor de venda", "Valor de aquisição", "CNPJ do Fornecedor", "Tamanho", "Estoque minimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        if(getQuantidade()==0){
            montarTabela();
        }else if(getQuantidade()==1){
            montarTabela1();
        }else if(getQuantidade()==2){
            montarTabela2();
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameExibirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExibirProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
