/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entidades.Funcionario;
import Entidades.Produto;
import Modal.Vender;
import Models.ModelFuncionario;
import Models.ModelProduto;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan
 */
public class FrameMenu extends javax.swing.JFrame {

    ModelFuncionario mf = new ModelFuncionario();
    ModelProduto mp = new ModelProduto();
    Funcionario logado = new Funcionario();
    int R = 0; //cuidar do array
    

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
        //System.out.println(logado.getId()+","+logado.getNome());
    }

    public boolean todosProdutos() {
        try {
            for (Produto p : mp.listaProdutos()) {
                if (p.getEstoque() <= p.getEstoqueMin()) {
                    return true;
                }
            }
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            return false;
        }

    }
    
    /*public void todosProdutos() {
        try {
            for (Produto p : mp.listaProdutos()) {
                if (p.getEstoque() <= p.getEstoqueMin()) {
                    R++;
                    nomeP[R] = p.getNome();
                    System.out.println(p.getNome()+"==="+R);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }*/

    public void aviso() {
        if (todosProdutos()==true) {

            FrameAviso fa = new FrameAviso();
            Desktop.add(fa);
            fa.montarTabela();
            //fa.R = this.R;
            fa.show();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        RH2 = new javax.swing.JButton();
        Cliente2 = new javax.swing.JButton();
        Vendas2 = new javax.swing.JButton();
        Produtos2 = new javax.swing.JButton();
        Fornecedores2 = new javax.swing.JButton();
        Fornecedores3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuGFuncionario = new javax.swing.JMenuItem();
        MenuGAdcFuncionario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ManuGCliente = new javax.swing.JMenuItem();
        MenuGAdcCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuGVendas = new javax.swing.JMenuItem();
        MenuGVender = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuGProdutos = new javax.swing.JMenuItem();
        MenuGAdcProduto = new javax.swing.JMenuItem();
        MenuGFornecedor = new javax.swing.JMenuItem();
        MenuGAdcFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuGSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Gerente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Desktop.setMaximumSize(new java.awt.Dimension(571, 478));
        Desktop.setMinimumSize(new java.awt.Dimension(571, 478));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        RH2.setText("RH");
        RH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RH2ActionPerformed(evt);
            }
        });

        Cliente2.setText("Cliente");
        Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente2ActionPerformed(evt);
            }
        });

        Vendas2.setText("Vendas");
        Vendas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendas2ActionPerformed(evt);
            }
        });

        Produtos2.setText("Produtos");
        Produtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos2ActionPerformed(evt);
            }
        });

        Fornecedores2.setText("Fornecedores");
        Fornecedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fornecedores2ActionPerformed(evt);
            }
        });

        Fornecedores3.setText(". . .");
        Fornecedores3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fornecedores3ActionPerformed(evt);
            }
        });

        jMenu1.setText("RH");

        MenuGFuncionario.setText("Funcionários");
        MenuGFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGFuncionario);

        MenuGAdcFuncionario.setText("Adicionar Funcionários");
        MenuGAdcFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGAdcFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGAdcFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Clientes");

        ManuGCliente.setText("Clientes");
        ManuGCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuGClienteActionPerformed(evt);
            }
        });
        jMenu3.add(ManuGCliente);

        MenuGAdcCliente.setText("Adicionar Cliente");
        MenuGAdcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGAdcClienteActionPerformed(evt);
            }
        });
        jMenu3.add(MenuGAdcCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Vendas");

        MenuGVendas.setText("Vendas");
        jMenu4.add(MenuGVendas);

        MenuGVender.setText("Realizar Venda");
        MenuGVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGVenderActionPerformed(evt);
            }
        });
        jMenu4.add(MenuGVender);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Produtos");

        MenuGProdutos.setText("Produtos");
        MenuGProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGProdutosActionPerformed(evt);
            }
        });
        jMenu5.add(MenuGProdutos);

        MenuGAdcProduto.setText("Adicionar Produto");
        MenuGAdcProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGAdcProdutoActionPerformed(evt);
            }
        });
        jMenu5.add(MenuGAdcProduto);

        MenuGFornecedor.setText("Fornecedores");
        MenuGFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGFornecedorActionPerformed(evt);
            }
        });
        jMenu5.add(MenuGFornecedor);

        MenuGAdcFornecedor.setText("Adicionar Fornecedor");
        MenuGAdcFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGAdcFornecedorActionPerformed(evt);
            }
        });
        jMenu5.add(MenuGAdcFornecedor);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Ações");

        MenuGSair.setText("Sair");
        jMenu2.add(MenuGSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RH2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cliente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vendas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Produtos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fornecedores2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fornecedores3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Vendas2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Produtos2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fornecedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fornecedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cliente2, Fornecedores2, Produtos2, RH2, Vendas2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*public void painel(){
        jPanel1.setLayout(null);
        jPanel1.setSize(142, 352);
        Desktop.setSize(571, 478);
    }*/

    private void MenuGFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGFuncionarioActionPerformed
        // TODO add your handling code here:
        openForm(new FrameFuncionario());

    }//GEN-LAST:event_MenuGFuncionarioActionPerformed

    private void openForm(JInternalFrame f) {
        Desktop.add(f);
        //f.centralizar();
        f.show();
    }

    private void MenuGAdcFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGAdcFuncionarioActionPerformed
        // TODO add your handling code here:
        /*FrameAdcFuncionario adcFunc = new FrameAdcFuncionario();
        Desktop.add(adcFunc);
        adcFunc.show();*/
        openForm(new FrameAdcFuncionario());

    }//GEN-LAST:event_MenuGAdcFuncionarioActionPerformed

    private void MenuGAdcFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGAdcFornecedorActionPerformed
        // TODO add your handling code here:
        //FrameAdcFornecedor adcForn = new FrameAdcFornecedor();
        openForm(new FrameAdcFornecedor());

    }//GEN-LAST:event_MenuGAdcFornecedorActionPerformed

    private void MenuGAdcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGAdcClienteActionPerformed
        // TODO add your handling code here:
        openForm(new FrameAdcCliente());

    }//GEN-LAST:event_MenuGAdcClienteActionPerformed

    private void MenuGAdcProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGAdcProdutoActionPerformed
        // TODO add your handling code here:

        openForm(new FrameAdcProduto());
    }//GEN-LAST:event_MenuGAdcProdutoActionPerformed

    private void ManuGClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuGClienteActionPerformed
        // TODO add your handling code here:

        openForm(new FrameClientes());
    }//GEN-LAST:event_ManuGClienteActionPerformed

    private void MenuGProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGProdutosActionPerformed
        // TODO add your handling code here:

        openForm(new FrameProduto());
    }//GEN-LAST:event_MenuGProdutosActionPerformed

    private void MenuGFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGFornecedorActionPerformed
        // TODO add your handling code here:

        openForm(new FrameFornecedor());
    }//GEN-LAST:event_MenuGFornecedorActionPerformed

    private void MenuGVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGVenderActionPerformed
        // TODO add your handling code here:
        openForm(new Vender());
    }//GEN-LAST:event_MenuGVenderActionPerformed

    private void RH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RH2ActionPerformed
        // TODO add your handling code here:
        openForm(new FrameFuncionario());
    }//GEN-LAST:event_RH2ActionPerformed

    private void Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente2ActionPerformed
        // TODO add your handling code here:
        openForm(new FrameClientes());
    }//GEN-LAST:event_Cliente2ActionPerformed

    private void Vendas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendas2ActionPerformed
        // TODO add your handling code here:
        //openForm(new FrameVenda());
        FrameVenda fv = new FrameVenda();
        fv.logado = this.logado;
        Desktop.add(fv);
        fv.show();
    }//GEN-LAST:event_Vendas2ActionPerformed

    private void Produtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos2ActionPerformed
        // TODO add your handling code here:
        openForm(new FrameProduto());
    }//GEN-LAST:event_Produtos2ActionPerformed

    private void Fornecedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fornecedores2ActionPerformed
        // TODO add your handling code here:
        openForm(new FrameFornecedor());
    }//GEN-LAST:event_Fornecedores2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //painel();
        aviso();
    }//GEN-LAST:event_formWindowOpened

    private void Fornecedores3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fornecedores3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_Fornecedores3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente2;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton Fornecedores2;
    private javax.swing.JButton Fornecedores3;
    private javax.swing.JMenuItem ManuGCliente;
    private javax.swing.JMenuItem MenuGAdcCliente;
    private javax.swing.JMenuItem MenuGAdcFornecedor;
    private javax.swing.JMenuItem MenuGAdcFuncionario;
    private javax.swing.JMenuItem MenuGAdcProduto;
    private javax.swing.JMenuItem MenuGFornecedor;
    private javax.swing.JMenuItem MenuGFuncionario;
    private javax.swing.JMenuItem MenuGProdutos;
    private javax.swing.JMenuItem MenuGSair;
    private javax.swing.JMenuItem MenuGVendas;
    private javax.swing.JMenuItem MenuGVender;
    private javax.swing.JButton Produtos2;
    private javax.swing.JButton RH2;
    private javax.swing.JButton Vendas2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
